import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import {StyledEngineProvider} from "@mui/material";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dota 2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StyledEngineProvider injectFirst>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center bg-steam-primary text-white font-trajan">
            {children}
          </main>
        </body>
      </html>
    </StyledEngineProvider>
  )
}
